spring.application.name=PrimeWallet

# ==================== DATABASE ====================
spring.datasource.url=jdbc:postgresql://localhost:5432/primewallet_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# ==================== HIBERNATE ====================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# ==================== JWT ====================
jwt.secret=UHJpbWVXYWxsZXRTdXBlclNlY3JldEtleUZvckpXVFRva2VuR2VuZXJhdGlvbjIwMjRNdXN0QmVBdExlYXN0MjU2Qml0cw==
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000

# ==================== REDIS ====================
spring.data.redis.host=localhost
spring.data.redis.port=6379

# ==================== KAFKA (Tạm tắt - Sprint 2 sẽ bật) ====================
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration

# ==================== SERVER ====================
server.port=8080