# ==================== SENSITIVE CONFIGURATIONS ====================
# File này chứa các thông tin bảo mật thật (Mật khẩu DB, JWT Secret, Key VNPAY)
# Đã được ignore trong .gitignore để KHÔNG đẩy lên Github.

# --- Database ---
spring.datasource.password=postgres

# --- JWT ---
jwt.secret=UHJpbWVXYWxsZXRTdXBlclNlY3JldEtleUZvckpXVFRva2VuR2VuZXJhdGlvbjIwMjRNdXN0QmVBdExlYXN0MjU2Qml0cw==

# --- VNPAY ---
vnpay.tmn-code=JQ55TVNT
vnpay.hash-secret=WBERNIKEGINIUAWOXDKXOEXMJDHPZCLM
vnpay.version=2.1.0
vnpay.command=pay
vnpay.order-type=other

# ===============================
# WEB3 / BLOCKCHAIN CONFIGURATION
# ===============================
# Mạng Sepolia Testnet công cộng (Có thể dùng Infura/Alchemy để ổn định hơn)
web3.rpc-url=https://rpc.sepolia.org
etherscan.api-key=YOUR_ETHERSCAN_API_KEY

et=WBERNIKEGINIUAWOXDKXOEXMJDHPZCLM
